# Generated by Django 3.0.8 on 2020-07-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardclub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image_url',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='styles',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='card',
            name='text_inner',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='card',
            name='text_outer',
            field=models.CharField(max_length=256),
        ),
    ]
