# Generated by Django 3.0.8 on 2020-07-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardclub', '0008_auto_20200706_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='styles',
            new_name='color',
        ),
        migrations.AddField(
            model_name='card',
            name='font',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='card',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
